name: Generate project.yml

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate spec
        run: xcodegen spec

      - name: Upload project.yml
        uses: actions/upload-artifact@v4
        with:
          name: project-yml
          path: project.yml
